apiVersion: batch/v1
kind: CronJob
metadata:
  name: financial-trading-crew
  namespace: o11y-4-ai-admehra
  labels:
    app: financial-trading-crew
    component: telemetry
  annotations:
    description: "Financial Trading CrewAI multi-agent with OpenTelemetry instrumentation"
spec:
  # Run every 4 hours from 8 AM to 4 PM PST on weekdays (Monday-Friday)
  schedule: "0 8,12,16 * * 1-5"
  timeZone: "America/Los_Angeles"
  suspend: false
  
  # Keep last 3 successful and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  
  jobTemplate:
    metadata:
      labels:
        app: financial-trading-crew
        component: telemetry
    spec:
      template:
        metadata:
          labels:
            app: financial-trading-crew
            component: telemetry
        spec:
          restartPolicy: OnFailure
          
          containers:
            - name: financial-trading-crew
              image: admehra621/financial-trading-crew:latest
              imagePullPolicy: Always
              
              env:
                # =============================================================================
                # Instrumentation Mode
                # =============================================================================
                # Set to "true" for manual instrumentation (in-code)
                # Set to "false" for zero-code instrumentation (opentelemetry-instrument)
                - name: OTEL_MANUAL_INSTRUMENTATION
                  value: "true"
                
                # =============================================================================
                # GenAI Semantic Conventions (REQUIRED)
                # =============================================================================
                - name: OTEL_SEMCONV_STABILITY_OPT_IN
                  value: "gen_ai_latest_experimental"
                
                # =============================================================================
                # OpenTelemetry Resource Attributes
                # =============================================================================
                - name: OTEL_RESOURCE_ATTRIBUTES
                  value: "deployment.environment=o11y-inframon-ai"
                
                # =============================================================================
                # Service Configuration
                # =============================================================================
                - name: OTEL_SERVICE_NAME
                  value: "financial-trading-crew"
                
                # =============================================================================
                # OpenAI Configuration
                # =============================================================================
                - name: OPENAI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: openai-credentials
                      key: api-key
                
                - name: OPENAI_MODEL_NAME
                  value: "gpt-4o-mini"
                
                # =============================================================================
                # Serper API Key for web search tool
                # =============================================================================
                - name: SERPER_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: openai-credentials
                      key: serper-api-key
                
                # =============================================================================
                # LLM OAuth2 Credentials (alternative to OpenAI API key)
                # =============================================================================
                - name: LLM_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: llm-credentials
                      key: client-id
                
                - name: LLM_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: llm-credentials
                      key: client-secret
                
                - name: LLM_TOKEN_URL
                  valueFrom:
                    secretKeyRef:
                      name: llm-credentials
                      key: token-url
                
                - name: LLM_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: llm-credentials
                      key: base-url
                
                - name: LLM_APP_KEY
                  valueFrom:
                    secretKeyRef:
                      name: llm-credentials
                      key: app-key
                
                # =============================================================================
                # CrewAI Configuration
                # =============================================================================
                - name: CREWAI_DISABLE_TELEMETRY
                  value: "true"
                
                # =============================================================================
                # Deepeval Telemetry Opt-Out
                # =============================================================================
                - name: DEEPEVAL_TELEMETRY_OPT_OUT
                  value: "YES"
                
                # =============================================================================
                # GenAI Content Capture
                # =============================================================================
                - name: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
                  value: "true"
                
                - name: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT_MODE
                  value: "SPAN_AND_EVENT"
                
                # =============================================================================
                # GenAI Emitters Configuration
                # =============================================================================
                - name: OTEL_INSTRUMENTATION_GENAI_EMITTERS
                  value: "span_metric"
                
                - name: OTEL_INSTRUMENTATION_GENAI_EMITTERS_EVALUATION
                  value: "replace-category:SplunkEvaluationResults"
                
                # =============================================================================
                # Evaluation Settings
                # =============================================================================
                - name: OTEL_INSTRUMENTATION_GENAI_EVALS_RESULTS_AGGREGATION
                  value: "true"
                
                # =============================================================================
                # OpenTelemetry Logs Exporter
                # =============================================================================
                - name: OTEL_LOGS_EXPORTER
                  value: "otlp"
                
                # =============================================================================
                # OTLP Endpoint Configuration
                # =============================================================================
                - name: SPLUNK_OTEL_AGENT
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: "http://$(SPLUNK_OTEL_AGENT):4317"
                
                - name: OTEL_EXPORTER_OTLP_PROTOCOL
                  value: "grpc"
                
                # =============================================================================
                # Exporter Configuration
                # =============================================================================
                - name: OTEL_TRACES_EXPORTER
                  value: "otlp"
                
                - name: OTEL_METRICS_EXPORTER
                  value: "otlp"
                
                - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
                  value: "DELTA"
                
                - name: OTEL_LOG_LEVEL
                  value: "info"
                
                # =============================================================================
                # Sampling Configuration
                # =============================================================================
                - name: OTEL_TRACES_SAMPLER
                  value: "parentbased_traceidratio"
                
                - name: OTEL_TRACES_SAMPLER_ARG
                  value: "1.0"
                
                # =============================================================================
                # Python Logging Configuration
                # =============================================================================
                - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
                  value: "true"
                
                - name: OTEL_PYTHON_LOG_CORRELATION
                  value: "true"
                
                # =============================================================================
                # CrewAI Instrumentation
                # =============================================================================
                - name: OTEL_INSTRUMENTATION_CREWAI_CAPTURE_MESSAGE_CONTENT
                  value: "true"
                
                # =============================================================================
                # Batch Span Processor Configuration (for short-lived containers)
                # =============================================================================
                - name: OTEL_BSP_SCHEDULE_DELAY
                  value: "1000"
                
                - name: OTEL_BSP_EXPORT_TIMEOUT
                  value: "30000"
                
                - name: OTEL_BSP_MAX_QUEUE_SIZE
                  value: "2048"
                
                - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
                  value: "512"
                
                # =============================================================================
                # Miscellaneous
                # =============================================================================
                - name: SPLUNK_PROFILER_ENABLED
                  value: "true"
                
                - name: PYTHONUNBUFFERED
                  value: "1"
                
                - name: OTEL_GENAI_EVALUATION_SAMPLING_RATE
                  value: "1"
              
              # Resource limits
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "500m"
                limits:
                  memory: "1Gi"
                  cpu: "1000m"

