apiVersion: v1
kind: Namespace
metadata:
  name: sre-copilot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-copilot-config
  namespace: sre-copilot
data:
  AZURE_EMBEDDING_DEPLOYMENT: text-embedding-3-large
  AZURE_OPENAI_API_VERSION: 2024-12-01-preview
  AZURE_OPENAI_ENDPOINT: https://o11y-for-ai-test.cognitiveservices.azure.com/
  CIRCUIT_BASE_URL: https://chat-ai.cisco.com/openai/deployments/gpt-4o-mini
  CIRCUIT_TOKEN_URL: https://id.cisco.com/oauth2/default/v1/token
  DEEPEVAL_FILE_SYSTEM: READ_ONLY
  DEEPEVAL_LLM_BASE_URL: https://o11y-for-ai-test.cognitiveservices.azure.com/openai/v1/
  DEEPEVAL_LLM_MODEL: gpt-4.1-nano
  DEEPEVAL_LLM_PROVIDER: openai
  DEEPEVAL_LLM_EXTRA_HEADERS: '{"api_version":"2024-12-01-preview"}'
  DEEPEVAL_MAX_CONCURRENT: "10"
  DEPLOYMENT_ENV: o11y-for-ai
  MCP_SERVER_URL: http://sre-copilot-mcp.sre-copilot.svc.cluster.local:8081
  OPENAI_MODEL: gpt-4o-mini
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: DELTA
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_GENAI_EVAL_DEBUG_EACH: "false"
  OTEL_GENAI_EVAL_DEBUG_SKIPS: "false"
  OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT: "true"
  OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT_MODE: SPAN_AND_EVENT
  OTEL_INSTRUMENTATION_GENAI_DEBUG: "false"
  OTEL_INSTRUMENTATION_GENAI_EMITTERS: span_metric_event,splunk
  OTEL_INSTRUMENTATION_GENAI_EMITTERS_EVALUATION: replace-category:SplunkEvaluationResults
  OTEL_INSTRUMENTATION_GENAI_EVALS_CONCURRENT: "true"
  OTEL_INSTRUMENTATION_GENAI_EVALS_RESULTS_AGGREGATION: "true"
  OTEL_INSTRUMENTATION_GENAI_EVALS_USE_SINGLE_METRIC: "true"
  OTEL_INSTRUMENTATION_GENAI_EVALS_WORKERS: "2"
  OTEL_INSTRUMENTATION_GENAI_EVALUATION_QUEUE_SIZE: "1000"
  OTEL_INSTRUMENTATION_GENAI_EVALUATION_RATE_LIMIT_BURST: "3"
  OTEL_INSTRUMENTATION_GENAI_EVALUATION_RATE_LIMIT_RPS: "0.5"
  OTEL_INSTRUMENTATION_LANGCHAIN_DEBUG: "false"
  OTEL_LOGS_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_PYTHON_LOG_LEVEL: debug
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=o11y-for-ai
  OTEL_TRACES_EXPORTER: otlp
  DEBUG_TOOLS: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: sre-copilot-secrets
  namespace: sre-copilot
type: Opaque
stringData:
  DEEPEVAL_LLM_API_KEY: "<YOUR_DEEPEVAL_LLM_API_KEY>"
  CIRCUIT_CLIENT_ID: "<YOUR_CIRCUIT_CLIENT_ID>"
  CIRCUIT_CLIENT_SECRET: "<YOUR_CIRCUIT_CLIENT_SECRET>"
  CIRCUIT_APP_KEY: "<YOUR_CIRCUIT_APP_KEY>"
  AZURE_OPENAI_API_KEY: "<YOUR_AZURE_OPENAI_API_KEY>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-copilot-api
  namespace: sre-copilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-copilot-api
  template:
    metadata:
      labels:
        app: sre-copilot-api
    spec:
      containers:
      - name: sre-copilot-api
        image: ertserendavga918/sre-copilot-api:v0.1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: sre-copilot-config
        - secretRef:
            name: sre-copilot-secrets
        env:
        - name: OTEL_SERVICE_NAME
          value: "sre-copilot"
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: sre-copilot-api
  namespace: sre-copilot
spec:
  selector:
    app: sre-copilot-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-copilot-mcp
  namespace: sre-copilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-copilot-mcp
  template:
    metadata:
      labels:
        app: sre-copilot-mcp
    spec:
      containers:
      - name: sre-copilot-mcp
        image: ertserendavga918/sre-copilot-mcp:v0.1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        envFrom:
        - configMapRef:
            name: sre-copilot-config
        - secretRef:
            name: sre-copilot-secrets
        env:
        - name: OTEL_SERVICE_NAME
          value: "sre-copilot-mcp"
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: sre-copilot-mcp
  namespace: sre-copilot
spec:
  selector:
    app: sre-copilot-mcp
  ports:
  - name: http
    port: 8081
    targetPort: 8081
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sre-copilot-run-scenario-001
  namespace: sre-copilot
spec:
  schedule: "*/10 * * * *"
  timeZone: "America/Los_Angeles"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: trigger
            image: curlimages/curl:8.5.0
            imagePullPolicy: IfNotPresent
            args:
            - -sS
            - -X
            - POST
            - http://sre-copilot-api.sre-copilot.svc.cluster.local:8080/run
            - -H
            - "Content-Type: application/json"
            - -d
            - '{"scenario_id":"scenario-001"}'
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
