---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-incident-copilot-config
  namespace: sre-copilot
data:
  OPENAI_MODEL: "gpt-4o-mini"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "DELTA"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
  OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT: "true"
  OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT_MODE: "SPAN_AND_EVENT"
  OTEL_INSTRUMENTATION_GENAI_EMITTERS: "span_metric_event,splunk"
  OTEL_INSTRUMENTATION_GENAI_EVALS_RESULTS_AGGREGATION: "true"
  OTEL_INSTRUMENTATION_GENAI_EMITTERS_EVALUATION: "replace-category:SplunkEvaluationResults"
  OTEL_INSTRUMENTATION_GENAI_DEBUG: "true"
  DEEPEVAL_FILE_SYSTEM: "READ_ONLY"
  DATA_DIR: "/app/data"
  ARTIFACTS_DIR: "/app/artifacts"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sre-incident-copilot-cronjob
  namespace: sre-copilot
  labels:
    app: sre-incident-copilot
    component: cronjob
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  
  jobTemplate:
    metadata:
      labels:
        app: sre-incident-copilot
        component: job
    spec:
      activeDeadlineSeconds: 900
      backoffLimit: 2
      
      template:
        metadata:
          labels:
            app: sre-incident-copilot
            component: pod
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          
          containers:
          - name: sre-incident-copilot
            image: sre-incident-copilot:latest
            imagePullPolicy: Always
            
            envFrom:
            - configMapRef:
                name: sre-incident-copilot-config
            
            env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sre-incident-copilot-secrets
                  key: openai-api-key
            - name: OTEL_SERVICE_NAME
              value: "sre-incident-copilot"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=o11y-inframon-ai"
            - name: SPLUNK_OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(SPLUNK_OTEL_AGENT):4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: SCENARIO_ID
              value: "scenario-001"  # Rotate through scenarios: scenario-001, scenario-002, etc.
            - name: HOME
              value: "/tmp"
            
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
            
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: false
            
            volumeMounts:
            - name: data-volume
              mountPath: /app/data
              readOnly: true
            - name: artifacts-volume
              mountPath: /app/artifacts
          
          volumes:
          - name: data-volume
            configMap:
              name: sre-incident-copilot-data
          - name: artifacts-volume
            emptyDir: {}

