apiVersion: v1
kind: Secret
metadata:
  name: ai-defense-collector-secrets
  namespace: ai-defense
type: Opaque
stringData:
  LAB0_ACCESS_TOKEN: "eeREGbOiLBfR5InYUBZmMw"
  RC0_ACCESS_TOKEN: "NgQlBLVQKGXqsd0jx82pjg"
  LAB0_HEC_TOKEN: "2b72a9ce-da3f-417b-90b3-30889de342ed"
  RC0_HEC_TOKEN: "3f380e1e-817f-4cb8-9292-39ca28b35fb7"
