apiVersion: batch/v1
kind: CronJob
metadata:
  name: travel-planner-openai-agents
  namespace: travel-planner
  labels:
    app: travel-planner-openai-agents
    component: telemetry
  annotations:
    description: "Multi-agent travel planner with OpenAI Agents SDK and OpenTelemetry instrumentation"
spec:
  schedule: "*/40 9-17 * * 1-5"
  timeZone: "America/Los_Angeles"
  suspend: false
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  
  jobTemplate:
    metadata:
      labels:
        app: travel-planner-openai-agents
        component: job
    spec:
      activeDeadlineSeconds: 900
      backoffLimit: 2
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          labels:
            app: travel-planner-openai-agents
            component: pod
        spec:
          restartPolicy: Never
          
          containers:
            - name: travel-planner-openai-agents
              image: ertserendavga918/travel-planner-openai-agents:v0.7
              imagePullPolicy: Always
              
              # Inject all non-sensitive config from ConfigMap
              envFrom:
                - configMapRef:
                    name: travel-planner-openai-agents-config
              
              env:
                # === Option 1: Standard OpenAI API Key ===
                # Uncomment if using standard OpenAI API
                # - name: OPENAI_API_KEY
                #   valueFrom:
                #     secretKeyRef:
                #       name: openai-credentials
                #       key: api-key
                
                # === OAuth2 LLM Provider ===
                - name: LLM_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: langgraph-travel-agent-langchain-secrets
                      key: llm-client-id
                
                - name: LLM_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: langgraph-travel-agent-langchain-secrets
                      key: llm-client-secret
                
                # === Home directory for non-root user ===
                - name: HOME
                  value: /tmp
                
                # === DeepEval LLM Credentials ===
                - name: DEEPEVAL_LLM_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: langgraph-travel-agent-langchain-secrets
                      key: llm-client-id
                
                - name: DEEPEVAL_LLM_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: langgraph-travel-agent-langchain-secrets
                      key: llm-client-secret
                
                # === OpenTelemetry Resource Attributes ===
                - name: OTEL_RESOURCE_ATTRIBUTES
                  value: "deployment.environment=o11y-inframon-ai"
                
                # === Dynamic: Get host IP for Splunk OTEL agent ===
                - name: SPLUNK_OTEL_AGENT
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                
                # === Dynamic: OTLP endpoint (uses SPLUNK_OTEL_AGENT) ===
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: "http://$(SPLUNK_OTEL_AGENT):4317"
              
              # === Security context ===
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: false
                runAsNonRoot: true
                runAsUser: 1000
              
              # === Resource limits ===
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "2Gi"
                  cpu: "1"
