apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
data:
  config.yaml: |
    model_list:
      - model_name: gpt-4.1
        litellm_params:
          model: gpt-4-turbo-preview
          api_key: os.environ/OPENAI_API_KEY
      - model_name: "cisco-llm"
        litellm_params:
          model: openai/gpt-4o-mini
          api_base: "https://chat-ai.cisco.com/openai/deployments/gpt-4o-mini"
          api_key: os.environ/CISCO_API_TOKEN  # Token fetched via OAuth2
          custom_llm_provider: openai

    litellm_settings:
      callbacks: ["otel", "cisco_callback.cisco_handler"]
      success_callback: ["otel"]
      failure_callback: ["otel"]

    general_settings:
      master_key: os.environ/LITELLM_PROXY_KEY  # Change this to a secure key in production
      otel: true  # Enable OpenTelemetry logging
      disable_spend_logs: true
      allow_user_auth: false
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  selector:
    app: litellm
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        # image: docker.litellm.ai/berriai/litellm:main-stable 
        image: keitdeck245/kdecker-litellm:cisco-provider # updates otel integration to 1.38, and adds cisco-llm model
        args:
          - "--config"
          - "/app/proxy_server_config.yaml"
        ports:
        - containerPort: 4000
        env:
        - name: LITELLM_OTEL_INTEGRATION_ENABLE_METRICS
          value: "true"
        - name: LITELLM_OTEL_INTEGRATION_ENABLE_EVENTS
          value: "true"
        - name: OTEL_SERVICE_NAME
          value: "litellm-proxy-server"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=o11y-inframon-ai"
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        volumeMounts:
        - name: config-volume
          mountPath: /app/proxy_server_config.yaml
          subPath: config.yaml
        envFrom:
        - secretRef:
            name: litellm-secrets
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file